/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

// Composant des flammes violettes
function PurpleFlames() {
  const particlesRef = useRef()
  
  // Crée les positions initiales des particules (une seule fois)
  const particleCount = 100 // Nombre de particules de flamme
  const particles = useMemo(() => {
    const temp = []
    for (let i = 0; i < particleCount; i++) {
      // Position aléatoire en cercle autour du dragon
      const angle = (i / particleCount) * Math.PI * 2
      const radius = 2 + Math.random() * 0.5 // Rayon du cercle
      const x = Math.cos(angle) * radius
      const z = Math.sin(angle) * radius
      const y = Math.random() * -3 // Commence en bas
      
      temp.push({
        position: new THREE.Vector3(x, y, z),
        speed: 0.5 + Math.random() * 0.5, // Vitesse de montée
        offset: Math.random() * Math.PI * 2 // Décalage pour l'oscillation
      })
    }
    return temp
  }, [])
  
  // Crée le buffer de positions
  const positions = useMemo(() => {
    const pos = new Float32Array(particleCount * 3)
    particles.forEach((particle, i) => {
      pos[i * 3] = particle.position.x
      pos[i * 3 + 1] = particle.position.y
      pos[i * 3 + 2] = particle.position.z
    })
    return pos
  }, [particles])
  
  // Animation des particules
  useFrame((state, delta) => {
    if (particlesRef.current) {
      const posArray = particlesRef.current.geometry.attributes.position.array
      
      particles.forEach((particle, i) => {
        // Monte vers le haut
        particle.position.y += particle.speed * delta
        
        // Oscillation gauche/droite (effet flamme)
        const oscillation = Math.sin(state.clock.elapsedTime * 2 + particle.offset) * 0.2
        
        // Rotation autour du dragon
        const angle = (i / particleCount) * Math.PI * 2 + state.clock.elapsedTime * 0.5
        const radius = 2 + Math.sin(state.clock.elapsedTime + particle.offset) * 0.3
        
        posArray[i * 3] = Math.cos(angle) * radius + oscillation
        posArray[i * 3 + 1] = particle.position.y
        posArray[i * 3 + 2] = Math.sin(angle) * radius
        
        // Réinitialise quand la particule est trop haute
        if (particle.position.y > 4) {
          particle.position.y = -1
        }
      })
      
      particlesRef.current.geometry.attributes.position.needsUpdate = true
    }
  })
  
  return (
    <points ref={particlesRef}>
      <bufferGeometry>
        <bufferAttribute
          attach="attributes-position"
          count={particleCount}
          array={positions}
          itemSize={3}
        />
      </bufferGeometry>
      <pointsMaterial
        size={0.15}
        color="#a855f7" // Violet (Tailwind purple-500)
        transparent
        opacity={0.6}
        blending={THREE.AdditiveBlending} // Effet lumineux
        depthWrite={false}
      />
    </points>
  )
}

export function BlackDragon(props) {
  const groupRef = useRef()
  const [isHovered, setIsHovered] = useState(true)
  
  const { nodes, materials } = useGLTF('/models/dragon+3d+model.glb')
  
  // Animation frame par frame (60fps) avec suivi de souris
  useFrame((state, delta) => {
    if (groupRef.current) {
      // EFFET RESPIRATION
      const breathingScale = 1 + Math.sin(state.clock.elapsedTime * 1.5) * 0.05
      
      // Applique le breathing au scale de base
      const targetScale = breathingScale
      groupRef.current.scale.x += (targetScale * (props.scale?.[0] || -5) - groupRef.current.scale.x) * delta * 3
      groupRef.current.scale.y += (targetScale * (props.scale?.[1] || 5) - groupRef.current.scale.y) * delta * 3
      groupRef.current.scale.z += (targetScale * (props.scale?.[2] || 5) - groupRef.current.scale.z) * delta * 3
      
      // SUIVI DE SOURIS ULTRA-SMOOTH
      // state.pointer donne la position de la souris entre -1 et 1 (x et y)
      const mouseX = state.pointer.x  // -1 (gauche) à 1 (droite)
      const mouseY = state.pointer.y  // -1 (bas) à 1 (haut)
      
      // Rotation Y (horizontal) : la tête suit la souris gauche/droite
      // Multiplie par 0.3 pour limiter l'angle (ne tourne pas trop)
      const targetRotationY = (props.rotation?.[1] || 4.7) + mouseX * 0.3
      groupRef.current.rotation.y += (targetRotationY - groupRef.current.rotation.y) * delta * 2
      
      // Rotation X (vertical) : la tête s'incline haut/bas
      const targetRotationX = (props.rotation?.[0] || 1.5) - mouseY * 0.2
      groupRef.current.rotation.x += (targetRotationX - groupRef.current.rotation.x) * delta * 2
      
      // Légère translation pour suivre la souris (effet parallaxe)
      const targetPosX = (props.position?.[0] || 0) + mouseX * 0.5
      const targetPosY = (props.position?.[1] || 1) + mouseY * 0.3
      groupRef.current.position.x += (targetPosX - groupRef.current.position.x) * delta * 1.5
      groupRef.current.position.y += (targetPosY - groupRef.current.position.y) * delta * 1.5
    }
  })
  
  return (
    <group 
      {...props} 
      dispose={null}
      ref={groupRef}
      // Détecte quand la souris entre sur le dragon
      onPointerEnter={() => setIsHovered(true)}
      // Détecte quand la souris quitte le dragon
      onPointerLeave={() => setIsHovered(false)}
      // Change le curseur en pointer au survol
      onPointerOver={(e) => { e.stopPropagation(); document.body.style.cursor = 'pointer' }}
      onPointerOut={(e) => { e.stopPropagation(); document.body.style.cursor = 'default' }}
    >
      <mesh
        geometry={nodes['tripo_node_62db38d2-5c56-4a09-b9ee-c4855ffd163a'].geometry}
        material={materials['tripo_mat_62db38d2-5c56-4a09-b9ee-c4855ffd163a']}
      />
      {/* Flammes violettes qui apparaissent au hover */}
      <PurpleFlames isActive={isHovered} />
    </group>
  )
}

useGLTF.preload('/models/dragon+3d+model.glb')
