/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ArachnoBoy (https://sketchfab.com/vang807)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/mega-wyvern-f8caf90ad5da4017b0dddfe880cf37cc
Title: Mega Wyvern
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'

export function Wyvern(props) {
  const group = useRef()
  const loopCount = useRef(0) // Compteur de répétitions
  const { nodes, materials, animations } = useGLTF('/models/mega_wyvern.glb')
  const { actions } = useAnimations(animations, group)
  
  useEffect(() => {
     // LOG toutes les animations disponibles
     console.log('🎬 Animations disponibles:', animations.map(anim => anim.name))
     console.log('📊 Nombre d\'animations:', animations.length)
     
     if (animations.length > 10) {
        // 1. Joue l'animation 10 UNE SEULE FOIS
        const action10 = actions[animations[10].name]
        const action0 = actions[animations[0].name]
        const action8 = actions[animations[8].name]
        
        // Configure l'animation 10 pour ne jouer qu'une fois
        action10.setLoop(THREE.LoopOnce, 1) // LoopOnce = joue 1 fois
        action10.clampWhenFinished = true   // Reste sur la dernière frame
        
        // 2. Écoute quand les animations se terminent ou bouclent
        const mixer = action10.getMixer()
        
        const onFinished = (e) => {
          if (e.action === action10) {
            console.log('✅ Animation 10 terminée, lance animation 0')

            // 3. Lance l'animation 0 en boucle
            loopCount.current = 0 // Réinitialise le compteur
            action0.reset()
            action0.setLoop(THREE.LoopRepeat) // Boucle infinie
            action0.fadeIn(0.5)
            action0.play()
          }
        }
        
        // Event qui se déclenche à chaque fin de boucle
        const onLoop = (e) => {
          if (e.action === action0) {
            loopCount.current++
            console.log(`🔁 Animation 0 : boucle ${loopCount.current}/8`)
            
            // Après 8 répétitions, lance l'animation 8
            if (loopCount.current >= 8) {
              console.log('✅ 8 boucles terminées, lance animation 8')
              
              action0.fadeOut(0.5)
              setTimeout(() => {
                action0.stop()
                
                // Lance l'animation 8 en boucle infinie
                action8.reset()
                action8.setLoop(THREE.LoopOnce, 1) // Joue 1 fois
                action8.clampWhenFinished = true
                action8.fadeIn(0.5)
                action8.play()
                setTimeout(() => { action8.paused = true }, 2100) // Met en pause après 2.1 secondes
              }, 500) // Attend la fin du fadeOut
            }
          }
        }
        
        mixer.addEventListener('finished', onFinished)
        mixer.addEventListener('loop', onLoop) // Écoute les boucles
        
        // Lance l'animation 10
        console.log('▶️ Animation 10 lancée:', animations[10].name)
        action10.play()
        
        // Cleanup : retire l'event listener quand le composant se démonte
        return () => {
          mixer.removeEventListener('finished', onFinished)
        }
     }
  }, [actions, animations])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.997}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]} scale={46.949}>
                <group name="Dragon_Boss_05fbx_1" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="Dragon_Boss_05_4">
                        <group name="Object_5_5">
                          <group name="GLTF_created_0">
                            <primitive object={nodes.GLTF_created_0_rootJoint} />
                            <skinnedMesh
                              name="Object_82"
                              geometry={nodes.Object_82.geometry}
                              material={materials.Dragon_Boss_05}
                              skeleton={nodes.Object_82.skeleton}
                            />
                            <group name="Object_8_8_correction">
                              <group name="Object_8_8" />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mega_wyvern.glb')
